



id: python-build
licenseUri: 
projectUri: 
iconUri:
copyright:
company:
authors: []
contributors: []
descripton: |
    downloads and builds python. 
tags: []
dependencies: 
  - name: 
    version: 

files:
 - private
 - public
 - package.yml

powershell:
  module: python-build.psm1
  functions:
  aliases:
  scripts:
  supportedEditions: 


