version: '2'

services:
  nerdymishka_mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 8081:3306
    environment:
      MYSQL_USER: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: nerdymishka_dev
      MYSQL_PASSWORD: wordpress
    networks:
      - backend

  nerdymishka_wordpress:
    depends_on:
      - nerdymishka_mysql
    image: wordpress
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins
      - ./themes:/var/www/html/wp-content/themes
      - ./uploads:/var/www/html/wp-content/uploads
    environment:
      VIRTUAL_HOST: nerdymishka.devlocal
      VIRTUAL_PORT: 8080
      WORDPRESS_DB_HOST: nerdymishka_mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - frontend
      - backend

networks:
  backend:
  frontend:
    external:
      name: proxy