
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Invoke-Psake "Build"'
    failOnStderr: true
    pwsh: true
    workingDirectory: './dotnet'
    #targetType: 'filePath' # Optional. Options: filePath, inline
    #filePath: # Required when targetType == FilePath
    #arguments: # Optional
    #script: '# Write your PowerShell commands here.Write-Host Hello World' # Required when targetType == Inline
    #errorActionPreference: 'stop' # Optional. Options: stop, continue, silentlyContinue
    #failOnStderr: false # Optional
    #ignoreLASTEXITCODE: false # Optional
    #pwsh: false # Optional
    #workingDirectory: # Optional